services:
  backend-app:
    image: N-Fahey/medimate-deployed-backend:test_0.1.0
    build:
      context: ./backend
      args:
        BUILD_TYPE: testing
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/medimate
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo
  frontend-app:
    image: N-Fahey/medimate-deployed-frontend:test_0.1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        BUILD_TYPE: testing
        API_URL: http://localhost:5000
    ports:
      - "80:5173"
    depends_on:
      - backend-app
  mongo:
    image: mongo
    volumes:
      - mongo-data-test:/data/db
volumes:
  mongo-data-test:
