services:
  backend-app:
    image: N-Fahey/medimate-deployed-backend:dev_0.1.0
    build:
      context: ./backend
      args:
        BUILD_TYPE: development
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      PORT: ${BACKEND_PORT}
      MONGODB_URI: ${MONGODB_URI}
    secrets:
      - jwt_secret
    depends_on:
      - mongo
    restart: unless-stopped
  frontend-app:
    image: N-Fahey/medimate-deployed-frontend:dev_0.1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        BUILD_TYPE: development
        API_URL: ${API_URL}
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend-app
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
      - mongo-data-dev:/data/db
    restart: unless-stopped
volumes:
  mongo-data-dev:

secrets:
  jwt_secret:
    file: ./.secrets/jwt_secret.txt
