services:
  backend-app:
    image: N-Fahey/medimate-deployed-backend:test_0.1.0
    build:
      context: ./backend
      args:
        BUILD_TYPE: testing
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      PORT: ${BACKEND_PORT}
      MONGODB_URI: ${MONGODB_URI}
    secrets:
      - jwt_secret
    depends_on:
      - mongo
  frontend-app:
    image: N-Fahey/medimate-deployed-frontend:test_0.1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        BUILD_TYPE: testing
        API_URL: ${API_URL}
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend-app
  mongo:
    image: mongo
    volumes:
      - mongo-data-test:/data/db
volumes:
  mongo-data-test:

secrets:
  jwt_secret:
    file: ./.secrets/jwt_secret.txt
