name: Build & Publish Containers

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: Production
            compose-file: docker-compose.prod.yml
            tag: prod
          - environment: Development
            compose-file: docker-compose.dev.yml
            tag: dev
          - environment: Testing
            compose-file: docker-compose.test.yml
            tag: test
    environment: ${{ matrix.environment }}
    env:
      JWT_SECRET: ${{ secrets.JWT_KEY }}
      FRONTEND_PORT: ${{ vars.FRONTEND_PORT }}
      BACKEND_PORT: ${{ vars.BACKEND_PORT }}
      MONGODB_URI: ${{ vars.MONGODB_URI }}
      API_URL: ${{ vars.API_URL }}
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 24

      - name: Login to GHCR registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata action
        uses: docker/metadata-action@v6.0.0
        id: meta
        with:
          images: ${{ env.REGISTRY }}/medimate-${{ matrix.tag }}

      - name: Build and push ${{ matrix.environment }} image
        uses: docker/bake-action@v7
        with:
          source: .
          push: true
          files: |
            ./${{ matrix.compose-file }}
          set: |
            *.tags=${{ steps.meta.outputs.tags }}
