name: Build & Publish Prod Container

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
        JWT_KEY: ${{ secrets.JWT_KEY }}
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Login to GHCR registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata action
        uses: docker/metadata-action@v6.0.0
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push prod image
        uses: docker/bake-action@v7
        with:
          source: .
          push: true
          files: |
            ./docker-compose.prod.yml
          set: |
            *.tags=${{ steps.meta.outputs.tags }}
